/**:
  ros__parameters:
    intersection:
      common:
        attention_area_margin: 0.5 # [m]
        attention_area_length: 200.0 # [m]
        attention_area_angle_threshold: 0.785 # [rad]
        stop_line_margin: 3.0
        intersection_velocity: 2.778 # 2.778m/s = 10.0km/h
        intersection_max_accel: 0.5 # m/ss
        stop_overshoot_margin: 0.5 # [m] overshoot margin for stuck, collision detection
        use_intersection_area: false
        path_interpolation_ds: 0.1 # [m]

      stuck_vehicle:
        use_stuck_stopline: true # stopline generated before the first conflicting area
        stuck_vehicle_detect_dist: 3.0 # this should be the length between cars when they are stopped. The actual stuck vehicle detection length will be this value + vehicle_length.
        stuck_vehicle_ignore_dist: 10.0 # obstacle stop max distance(5.0m) + stuck vehicle size / 2 (0.0m-)
        stuck_vehicle_vel_thr: 0.833 # 0.833m/s = 3.0km/h
        # enable_front_car_decel_prediction: false # By default this feature is disabled
        # assumed_front_car_decel: 1.0 # [m/ss] the expected deceleration of front car when front car as well as ego are turning
        timeout_private_area: 3.0 # [s] cancel stuck vehicle stop in private area

      collision_detection:
        state_transit_margin_time: 1.0
        min_predicted_path_confidence: 0.05
        minimum_ego_predicted_velocity: 1.388 # [m/s]
        collision_start_margin_time: 4.0 # [s] this + state_transit_margin_time should be higher to account for collision with fast/accelerating object
        collision_end_margin_time: 6.0 # [s] this + state_transit_margin_time should be higher to account for collision with slow/decelerating object
        keep_detection_vel_thr: 0.833 # == 3.0km/h. keep detection if ego is ego.vel < keep_detection_vel_thr

      occlusion:
        enable: false
        occlusion_attention_area_length: 70.0 # [m]
        enable_creeping: false # flag to use the creep velocity when reaching occlusion limit stop line
        occlusion_creep_velocity: 0.8333 # the creep velocity to occlusion limit stop line
        peeking_offset: -0.5 # [m] offset for peeking into detection area
        free_space_max: 43
        occupied_min: 58
        do_dp: true
        before_creep_stop_time: 0.1 # [s]
        min_vehicle_brake_for_rss: -2.5 # [m/s^2]
        max_vehicle_velocity_for_rss: 16.66 # [m/s] == 60kmph
        denoise_kernel: 1.0 # [m]
        pub_debug_grid: false

    merge_from_private:
      stop_duration_sec: 1.0
