/**:
  ros__parameters:
    enable_whole_load: true
    enable_downsampled_whole_load: false
    enable_partial_load: false
    enable_differential_load: false
    enable_selected_load: false

    # only used when downsample_whole_load enabled
    leaf_size: 0.05 # downsample leaf size [m]
