/**:
  ros__parameters:
    # use downsample filter before compare map
    use_down_sample_filter: False

    # voxel size for downsample filter
    down_sample_voxel_size: 0.1

    # distance threshold for compare compare
    distance_threshold: 0.5

    # publish voxelized map pointcloud for debug
    publish_debug_pcd: False

    # use dynamic map loading
    use_dynamic_map_loading: True

    # time interval to check dynamic map loading
    timer_interval_ms: 100

    # distance threshold for dynamic map update
    map_update_distance_threshold: 10.0

    # radius map for dynamic map loading
    map_loader_radius: 150.0
